name: bifrost_dev_run_launcher_v2.3.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argh=0.31.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - coverage=7.6.3=py313h536fd9c_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gprof2dot=2024.6.6=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgomp=14.1.0=h77fa898_1
  - libidn2=2.3.7=hd590300_0
  - libmpdec=4.0.0=h4bc722e_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pip=24.2=pyh145f28c_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pytest=8.3.3=pyhd8ed1ab_0
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - pytest-profiling=1.7.0=py_1
  - python=3.13.0=h9ebbce0_100_cp313
  - python_abi=3.13=5_cp313
  - pyyaml=6.0.2=py313h536fd9c_1
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - rpds-py=0.20.0=py313h920b4c0_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - watchdog=5.0.3=py313h78bf25f_0
  - wget=1.21.4=hda4d442_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - bifrostlib==2.1.17
      - dnspython==2.7.0
      - jsmin==3.0.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - libmagic==1.0
      - numpy==2.1.2
      - pandas==2.2.3
      - pymongo==4.10.1
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - pytz==2024.2
      - tzdata==2024.2
      - warlock==2.0.1
      - -e .